

//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace DbPastel
{

using System;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;

using System.Data.Entity.Core.Objects;
using System.Linq;


public partial class pasteleriaEntities : DbContext
{
    public pasteleriaEntities()
        : base("name=pasteleriaEntities")
    {

    }

    protected override void OnModelCreating(DbModelBuilder modelBuilder)
    {
        throw new UnintentionalCodeFirstException();
    }


    public virtual DbSet<Categoria> Categoria { get; set; }

    public virtual DbSet<Perfil> Perfil { get; set; }

    public virtual DbSet<Producto> Producto { get; set; }

    public virtual DbSet<Usuario> Usuario { get; set; }

    public virtual DbSet<boleta> boleta { get; set; }


    public virtual ObjectResult<pa_Login_Result> pa_Login(string email, string pass)
    {

        var emailParameter = email != null ?
            new ObjectParameter("email", email) :
            new ObjectParameter("email", typeof(string));


        var passParameter = pass != null ?
            new ObjectParameter("pass", pass) :
            new ObjectParameter("pass", typeof(string));


        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<pa_Login_Result>("pa_Login", emailParameter, passParameter);
    }


    public virtual ObjectResult<pa_ListarUsuario_Result> pa_ListarUsuario()
    {

        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<pa_ListarUsuario_Result>("pa_ListarUsuario");
    }


    public virtual ObjectResult<pa_BajarUsuario_Result> pa_BajarUsuario(Nullable<int> idUsuario)
    {

        var idUsuarioParameter = idUsuario.HasValue ?
            new ObjectParameter("idUsuario", idUsuario) :
            new ObjectParameter("idUsuario", typeof(int));


        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<pa_BajarUsuario_Result>("pa_BajarUsuario", idUsuarioParameter);
    }


    public virtual ObjectResult<pa_ListarProducto_Result> pa_ListarProducto()
    {

        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<pa_ListarProducto_Result>("pa_ListarProducto");
    }


    public virtual ObjectResult<pa_GuardarProducto_Result> pa_GuardarProducto(Nullable<int> idProducto, Nullable<int> idCategoria, string nombreProducto, string precioProducto, string descripcion)
    {

        var idProductoParameter = idProducto.HasValue ?
            new ObjectParameter("idProducto", idProducto) :
            new ObjectParameter("idProducto", typeof(int));


        var idCategoriaParameter = idCategoria.HasValue ?
            new ObjectParameter("idCategoria", idCategoria) :
            new ObjectParameter("idCategoria", typeof(int));


        var nombreProductoParameter = nombreProducto != null ?
            new ObjectParameter("nombreProducto", nombreProducto) :
            new ObjectParameter("nombreProducto", typeof(string));


        var precioProductoParameter = precioProducto != null ?
            new ObjectParameter("precioProducto", precioProducto) :
            new ObjectParameter("precioProducto", typeof(string));


        var descripcionParameter = descripcion != null ?
            new ObjectParameter("descripcion", descripcion) :
            new ObjectParameter("descripcion", typeof(string));


        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<pa_GuardarProducto_Result>("pa_GuardarProducto", idProductoParameter, idCategoriaParameter, nombreProductoParameter, precioProductoParameter, descripcionParameter);
    }


    public virtual ObjectResult<pa_BajarProducto_Result> pa_BajarProducto(Nullable<int> idProducto)
    {

        var idProductoParameter = idProducto.HasValue ?
            new ObjectParameter("idProducto", idProducto) :
            new ObjectParameter("idProducto", typeof(int));


        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<pa_BajarProducto_Result>("pa_BajarProducto", idProductoParameter);
    }


    public virtual ObjectResult<pa_RegistrarUsuario_Result> pa_RegistrarUsuario(Nullable<int> idUsuario, string nombre, string apellido, string email, string pass, Nullable<int> idPerfil)
    {

        var idUsuarioParameter = idUsuario.HasValue ?
            new ObjectParameter("idUsuario", idUsuario) :
            new ObjectParameter("idUsuario", typeof(int));


        var nombreParameter = nombre != null ?
            new ObjectParameter("nombre", nombre) :
            new ObjectParameter("nombre", typeof(string));


        var apellidoParameter = apellido != null ?
            new ObjectParameter("apellido", apellido) :
            new ObjectParameter("apellido", typeof(string));


        var emailParameter = email != null ?
            new ObjectParameter("email", email) :
            new ObjectParameter("email", typeof(string));


        var passParameter = pass != null ?
            new ObjectParameter("pass", pass) :
            new ObjectParameter("pass", typeof(string));


        var idPerfilParameter = idPerfil.HasValue ?
            new ObjectParameter("idPerfil", idPerfil) :
            new ObjectParameter("idPerfil", typeof(int));


        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<pa_RegistrarUsuario_Result>("pa_RegistrarUsuario", idUsuarioParameter, nombreParameter, apellidoParameter, emailParameter, passParameter, idPerfilParameter);
    }


    public virtual ObjectResult<pa_ListarUsuarioNoVigente_Result> pa_ListarUsuarioNoVigente()
    {

        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<pa_ListarUsuarioNoVigente_Result>("pa_ListarUsuarioNoVigente");
    }


    public virtual ObjectResult<pa_SubirUsuario_Result> pa_SubirUsuario(Nullable<int> idUsuario)
    {

        var idUsuarioParameter = idUsuario.HasValue ?
            new ObjectParameter("idUsuario", idUsuario) :
            new ObjectParameter("idUsuario", typeof(int));


        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<pa_SubirUsuario_Result>("pa_SubirUsuario", idUsuarioParameter);
    }


    public virtual ObjectResult<pa_ListarProductoNoVigente_Result> pa_ListarProductoNoVigente()
    {

        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<pa_ListarProductoNoVigente_Result>("pa_ListarProductoNoVigente");
    }


    public virtual ObjectResult<pa_SubirProducto_Result> pa_SubirProducto(Nullable<int> idProducto)
    {

        var idProductoParameter = idProducto.HasValue ?
            new ObjectParameter("idProducto", idProducto) :
            new ObjectParameter("idProducto", typeof(int));


        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<pa_SubirProducto_Result>("pa_SubirProducto", idProductoParameter);
    }


    public virtual ObjectResult<pa_ObtenerDatoProducto_Result> pa_ObtenerDatoProducto(Nullable<int> idProducto)
    {

        var idProductoParameter = idProducto.HasValue ?
            new ObjectParameter("idProducto", idProducto) :
            new ObjectParameter("idProducto", typeof(int));


        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<pa_ObtenerDatoProducto_Result>("pa_ObtenerDatoProducto", idProductoParameter);
    }


    public virtual ObjectResult<pa_ObtenerDatoUsuario_Result> pa_ObtenerDatoUsuario(Nullable<int> idUsuario)
    {

        var idUsuarioParameter = idUsuario.HasValue ?
            new ObjectParameter("idUsuario", idUsuario) :
            new ObjectParameter("idUsuario", typeof(int));


        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<pa_ObtenerDatoUsuario_Result>("pa_ObtenerDatoUsuario", idUsuarioParameter);
    }


    public virtual ObjectResult<pa_ListarCategoria_Result> pa_ListarCategoria()
    {

        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<pa_ListarCategoria_Result>("pa_ListarCategoria");
    }


    public virtual ObjectResult<pa_ObtenerDatoCategoria_Result> pa_ObtenerDatoCategoria(Nullable<int> idCategoria)
    {

        var idCategoriaParameter = idCategoria.HasValue ?
            new ObjectParameter("idCategoria", idCategoria) :
            new ObjectParameter("idCategoria", typeof(int));


        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<pa_ObtenerDatoCategoria_Result>("pa_ObtenerDatoCategoria", idCategoriaParameter);
    }


    public virtual ObjectResult<pa_GuardarCategoria_Result> pa_GuardarCategoria(Nullable<int> idCategoria, string nombreCategoria, Nullable<bool> vigente)
    {

        var idCategoriaParameter = idCategoria.HasValue ?
            new ObjectParameter("idCategoria", idCategoria) :
            new ObjectParameter("idCategoria", typeof(int));


        var nombreCategoriaParameter = nombreCategoria != null ?
            new ObjectParameter("nombreCategoria", nombreCategoria) :
            new ObjectParameter("nombreCategoria", typeof(string));


        var vigenteParameter = vigente.HasValue ?
            new ObjectParameter("vigente", vigente) :
            new ObjectParameter("vigente", typeof(bool));


        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<pa_GuardarCategoria_Result>("pa_GuardarCategoria", idCategoriaParameter, nombreCategoriaParameter, vigenteParameter);
    }

}

}

