
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace DbPastel
{

using System;
    using System.Collections.Generic;
    
public partial class Boleta
{

    public int idBoleta { get; set; }

    public Nullable<int> idCliente { get; set; }

    public Nullable<int> idProducto { get; set; }

    public Nullable<int> idCategoria { get; set; }

    public Nullable<int> precio { get; set; }

    public Nullable<System.DateTime> fechaCreacion { get; set; }

}

}
